# Generated by Django 3.0.7 on 2020-06-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Createstory',
            fields=[
                ('idcreatestory', models.IntegerField(db_column='idCreateStory', primary_key=True, serialize=False)),
                ('createstorycol', models.CharField(blank=True, db_column='CreateStorycol', max_length=45, null=True)),
            ],
            options={
                'db_table': 'CreateStory',
                'managed': False,
            },
        ),
    ]
