# Generated by Django 3.0.7 on 2020-08-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utory_api', '0002_auto_20200620_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deneme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=64, null=True)),
                ('roleid', models.IntegerField(blank=True, db_column='roleId', null=True)),
                ('published', models.BooleanField(blank=True, default=False, null=True)),
                ('approved', models.BooleanField(blank=True, default=False, null=True)),
                ('review', models.BooleanField(blank=True, default=False, null=True)),
                ('seen', models.BooleanField(blank=True, default=False, null=True)),
                ('resuming', models.BooleanField(blank=True, default=False, null=True)),
                ('trash', models.BooleanField(blank=True, default=False, null=True)),
                ('title', models.CharField(max_length=64)),
            ],
        ),
    ]
