# Generated by Django 3.0.7 on 2020-08-03 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utory_api', '0003_deneme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deneme',
            new_name='MyStories',
        ),
    ]
