# Generated by Django 3.0.7 on 2020-08-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utory_api', '0004_auto_20200803_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystories',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mystories',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mystories',
            name='resuming',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mystories',
            name='review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mystories',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mystories',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
