# Generated by Django 3.0.7 on 2020-08-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utory_api', '0005_auto_20200803_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystories',
            name='playcount',
            field=models.IntegerField(db_column='playCount', default=0),
        ),
        migrations.AddField(
            model_name='mystories',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
