# Generated by Django 3.0.7 on 2020-08-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utory_api', '0006_auto_20200806_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystories',
            name='username',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
